language: go
os:
  - linux
  - osx
  - windows
go:
  - '1.7'
  - '1.8'
  - '1.9'
  - '1.10'
  - '1.11'
  - '1.12'
  - '1.13'
  - '1.14'
  - '1.15'
before_install:
  - go get ./...
  - go install .
script:
  - goveralls
